### ISSUE TITLE
GitBook Documentation: Frappe settings

### ISSUE THREAD

**Issue by salmanulfarzy** [bailabs/tailpos-sync#1]
It was mentioned in [syncing-to-frappe-erpnext](https://docs.tailpos.com/tailpos/syncing-to-frappe-erpnext) page to modify `frappe/app.py` to include `make_form_dict` function. But isn't that already part of [v10] and [v11] ? (referencing specific commits from respective branches)

[v10]: https://github.com/frappe/frappe/blob/92dc1e0366d45cfc7b070a15ee7dcf25df3b3959/frappe/app.py#L123-L136
[v11]: https://github.com/frappe/frappe/blob/37fa2dc7f60454fc140f8686e077c33fedf41ca8/frappe/app.py#L122-L138

**Comment by iRaySpace** [comment]
Hello @salmanulfarzy,
If you are in the Frappe v10 or v11, you are good to go.

**Comment by salmanulfarzy** [comment]
It would be great if it's documented, Like only Frappe < 10 require that change.

**Comment by iRaySpace** [comment]
Thanks for pointing out. Your help is appreciated!
