### ISSUE TITLE
Fix: Generate Sales Invoice 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos-sync#11]
Generate sales invoice option not working. 

Please fix this issue.

![image](https://user-images.githubusercontent.com/12432802/59403016-9593ed80-8da9-11e9-9eef-8b61909c7c62.png)

**Comment by iRaySpace** [comment]
Hello. The team added Generation of Sales Invoice per hour interval. Don't forget to set Generate Limit under Tail Settings also.

**Comment by sammish** [comment]
Please check #13 

Please change generate limit to generate time.  For example if we set 12PM every day. System automatically check that time and there is any pending receipt sytem will generate automatically to invoice.

**Comment by iRaySpace** [comment]
@sammish The team will check on generation by time.
