### ISSUE TITLE
Fix : tailpos_sync.background_jobs.generate_si_from_receipts

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos-sync#13]
tailpos_sync.background_jobs.generate_si_from_receipts
![image](https://user-images.githubusercontent.com/12432802/61593888-20100e00-abee-11e9-973c-c285bdc690a9.png)
![image](https://user-images.githubusercontent.com/12432802/61594003-5ef29380-abef-11e9-9841-a1adad9ec505.png)

**Comment by sammish** [comment]
@iRaySpace @ccfiel please do needful.

**Comment by jiloysss** [comment]
Hello @sammish can you trigger save in tail settings to update the database. It will return an error because the value of Generate Limit in the database is None (this means NULL)

**Comment by sammish** [comment]
Hello @jiloysss 

![image](https://user-images.githubusercontent.com/12432802/61605527-a1978880-ac4e-11e9-87a3-a2c90d8de7cd.png)

**Comment by sammish** [comment]
@jiloysss 

After this updation also showing like that 

![image](https://user-images.githubusercontent.com/12432802/61605547-bbd16680-ac4e-11e9-8383-5f8e51abd3de.png)

**Comment by sammish** [comment]
@jiloysss same error 

![image](https://user-images.githubusercontent.com/12432802/61605594-f4714000-ac4e-11e9-99c8-8875f25710ed.png)

**Comment by iRaySpace** [comment]
Hello @sammish Have you set your Tail Settings? POS Profile and others.

**Comment by sammish** [comment]
@iRaySpace I will update you after going live.

**Comment by sammish** [comment]
@iRaySpace this is working without error.

**Comment by sammish** [comment]
@iRaySpace Not working 
![Peek 2019-08-18 15-10](https://user-images.githubusercontent.com/12432802/63224275-8e82c480-c1ca-11e9-9ace-4296e49eca42.gif)
