### ISSUE TITLE
Fix : Company not found

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos-sync#7]
After Updation Issue is that Company not Found
![image](https://user-images.githubusercontent.com/12432802/57522725-a0331100-732b-11e9-8db3-fc6413eb48ca.png)

**Comment by sammish** [comment]
Fix :Automatically Creating Default Customer 

![image](https://user-images.githubusercontent.com/12432802/57522779-bb9e1c00-732b-11e9-94ef-6256600690b3.png)

**Comment by iRaySpace** [comment]
Hello Sammish. Please set your default company for the POS Profile. For the default customer, it is by default created.

**Comment by sammish** [comment]
@iRaySpace that was stetted but not working

**Comment by iRaySpace** [comment]
Hello @sammish 
Can you update your instance and update `Use Device Profile` field?
![image](https://user-images.githubusercontent.com/5818544/57667725-379fa900-7637-11e9-8052-fb9379b5633e.png)

**Comment by sammish** [comment]
@iRaySpace this is working now.
