### ISSUE TITLE
Fix : Change cash/card setting to device 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos-sync#9]
Kindly change cash/card setting in device because multiple restaurant handling multiple cash-in-hand 

here to
![image](https://user-images.githubusercontent.com/12432802/57866216-a895bb00-7807-11e9-9e0a-54310591e03f.png)

there 
![image](https://user-images.githubusercontent.com/12432802/57866265-bc412180-7807-11e9-9eb9-8b8161ca31b8.png)

**Comment by iRaySpace** [comment]
Updated this one. Please bench update

**Comment by sammish** [comment]
okay working now @iRaySpace
